baseURL = "https://www.example.com"
languageCode = "en-us"
title = "Hashem A. Damrah"
copyright = "Copyright © 2021, Hashem A. Damrah; all rights reserved."
theme = "npq-hugo"
pygmentsUseClasses=true

[params]
  author = "Hashem A. Damrah"
  description = "your description"
  keywords = "hugo blog"
  useAvatar = true
  microBlogSection = "posts"
  displayMicroBlog = true
  displayRecent = true
  recentMax = 4
  mail = "dermdorm2@gmail.com"
  #phone = "8888888888"
  formspreeID = "http://formspree.io/dermdorm2@gmail.com"

[menu]
  [[menu.main]]
    name = "home"
    pre = "<i class=\"fas fa-home fa-sm\"></i>"
    url = "/"
    weight = -9 
  [[menu.main]]
    name = "tags"
    pre = "<i class=\"fas fa-tags fa-ms\"></i>"
    url = "/tags"
    weight = -8 
  [[menu.main]]
    name = "github"
    pre = "<i class=\"fab fa-github fa-ms\"></i>"
    url = "https://github.com/SingularisArt"
    weight = -6 
  [[menu.main]]
    name = "RSS"
    pre = "<i class=\"fas fa-rss fa-ms\"></i>"
    url = "/index.xml"
    weight = -5 
  [[menu.main]]
    name = "contact"
    pre = "<i class=\"far fa-envelope\"></i>"
    url = "/contact"
    weight = -4 

[taxonomia]
  tags = ""
