baseURL = "https://damrah.netlify.app"
title = "Hashem A. Damrah"
theme = "m10c"
paginate = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.main]]
    identifier = "notes"
    name = "Notes"
    url = "/notes/"
    weight = 4
  [[menu.main]]
    identifier = "tutorials"
    name = "Tutorials"
    url = "/tutorials/"
    weight = 5

[params]
  author = "Hashem A. Damrah"
  description = "ADD DESCRIPTION"
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/SingularisArt"
