baseURL = "https://damrah.netlify.app"
title = "My Blog"
theme = "m10c"
paginate = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3

[params]
  author = "Hashem A. Damrah"
  avatar = "profile.jpg"
  description = "ADD DESCRIPTION"
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/SingularisArt"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
